USE cafe_management;

-- Q11. Show each order with customer name.
SELECT o.order_id, c.customer_name, o.order_date, o.order_status
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id;

-- Q12. Show order details with product names.
SELECT oi.order_id, p.product_name, oi.quantity, oi.unit_price
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
ORDER BY oi.order_id;

-- Q13. Calculate total value of every order.
SELECT
    order_id,
    SUM(quantity * unit_price) AS order_total
FROM order_items
GROUP BY order_id
ORDER BY order_total DESC;

-- Q14. Count orders placed by each customer.
SELECT
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_orders DESC;

-- Q15. Calculate revenue generated by each product.
SELECT
    p.product_name,
    SUM(oi.quantity * oi.unit_price) AS revenue
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed'
GROUP BY p.product_id, p.product_name
ORDER BY revenue DESC;

-- Q16. Find total quantity sold for each product.
SELECT
    p.product_name,
    SUM(oi.quantity) AS total_units_sold
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed'
GROUP BY p.product_id, p.product_name
ORDER BY total_units_sold DESC;

-- Q17. Find customers who placed more than one order.
SELECT
    c.customer_name,
    COUNT(o.order_id) AS order_count
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
WHERE o.order_status <> 'Cancelled'
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) > 1;

-- Q18. Revenue by payment method.
SELECT
    o.payment_method,
    SUM(oi.quantity * oi.unit_price) AS revenue
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
GROUP BY o.payment_method
ORDER BY revenue DESC;

-- Q19. Average order value.
SELECT AVG(order_total) AS average_order_value
FROM (
    SELECT o.order_id, SUM(oi.quantity * oi.unit_price) AS order_total
    FROM orders o
    JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.order_status = 'Completed'
    GROUP BY o.order_id
) x;

-- Q20. Employees who handled more than 4 completed orders.
SELECT
    e.employee_name,
    COUNT(o.order_id) AS completed_orders
FROM employees e
JOIN orders o ON e.employee_id = o.employee_id
WHERE o.order_status = 'Completed'
GROUP BY e.employee_id, e.employee_name
HAVING COUNT(o.order_id) > 4;

-- Q21. Products with price between 100 and 200.
SELECT * FROM products
WHERE price BETWEEN 100 AND 200;

-- Q22. Find customers who have never placed an order.
SELECT c.customer_id, c.customer_name
FROM customers c
LEFT JOIN orders o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

-- Q23. Find products that have never been sold.
SELECT p.product_id, p.product_name
FROM products p
LEFT JOIN order_items oi ON p.product_id = oi.product_id
WHERE oi.product_id IS NULL;

-- Q24. Show each completed order with calculated total.
SELECT
    o.order_id,
    c.customer_name,
    o.order_date,
    SUM(oi.quantity * oi.unit_price) AS order_total
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
GROUP BY o.order_id, c.customer_name, o.order_date
ORDER BY o.order_date;
